kind: "Deployment"
replicaCount: 1

podSecurityPolicy:
  enabled: false

plugins:
  - fluent-plugin-cloudwatch-logs
  - fluent-plugin-grafana-loki

envFrom:
- secretRef:
    name: fluentd-aws-secrets

fileConfigs:
  01_sources.conf: |-
    <source>
      @type cloudwatch_logs
      tag cloudwatch.in
      use_aws_timestamp true
      fetch_interval 30 #in seconds
      start_time "2023-01-01 00:00:00Z"
      use_log_stream_name_prefix true

      region "#{ENV['AWS_REGION']}"
      aws_key_id "#{ENV['AWS_ACCESS_KEY']}" 
      aws_sec_key "#{ENV['AWS_SECRET_KEY']}"  
      log_group_name "#{ENV['CW_LOG_GROUP']}" 
      log_stream_name "#{ENV['CW_LOG_STREAM_PREFIX']}" 

      <parse>
        @type none
      </parse>
    </source>

  02_filters.conf: ""

  03_dispatch.conf: ""

  04_outputs.conf: |-
    <match **>
      @type loki
      url "http://loki-gateway:80"
      flush_interval 10s
      buffer_chunk_limit 1m
      extra_labels {"source": "cloudwatch"}
    </match>
