loki:
  auth_enabled: false

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

  limits_config:
    enforce_metric_name: false
    reject_old_samples: false
    reject_old_samples_max_age: 3y
    max_cache_freshness_per_query: 1m
    split_queries_by_interval: 30m

  rulerConfig:
    storage:
      local:
        directory: /var/loki/rules
      type: local

  storage:
    type: s3
    bucketNames:
      chunks: loki-storage-example # TODO: change
      ruler: loki-storage-example # TODO: change
      admin: loki-storage-example # TODO: change
    s3:
      region: eu-west-1 # TODO: change
      insecure: false
      s3forcepathstyle: true

  # The storage_config block configures one of many possible stores for both the
  # index and chunks. Which configuration to be picked should be defined in
  # schema_config block.
  storage_config:
    named_stores:
      aws:
        aws-store-1:
          endpoint: s3://loki-storage-example # TODO: change
          region: eu-west-1 # TODO: change
          signature_version: "v4"
          storage_class: "STANDARD"

    # Configures storing index in an Object Store (GCS/S3/Azure/Swift/Filesystem) in
    # the form of boltdb files. Required fields only required when boltdb-shipper is
    # defined in config.
    boltdb_shipper:
      active_index_directory: /var/loki/index
      shared_store: s3
      cache_location: /var/loki/boltdb-cache

  # Configures the chunk index schema and where it is stored.
  schema_config:
    configs:
      - from: "2020-01-01"
        schema: v11
        store: boltdb-shipper
        object_store: aws-store-1
        index:
          period: 24h
          prefix: loki_index_

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXX:role/logging-loki-role # TODO: change
  create: true
  name: loki-sa

monitoring:
  alerts:
    enabled: false
  dashboards:
    enabled: false
  rules:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
  serviceMonitor:
    enabled: false
test:
  enabled: false
read:
  replicas: 1
backend:
  replicas: 1
  persistence:
    enableStatefulSetAutoDeletePVC: true
    size: 4Gi
write:
  replicas: 1
  terminationGracePeriodSeconds: 60
  persistence:
    enableStatefulSetAutoDeletePVC: true
    size: 4Gi
gateway:
  replicas: 1
  service:
    type: ClusterIP
