apiVersion: v1
kind: ConfigMap
metadata:
  name: log-generator-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app.log
      pos_file /var/log/app.log.pos
      refresh_interval 1
      tag log-generator
      <parse>
        @type none
      </parse>
    </source>

    <match log-generator>
      @type cloudwatch_logs
      region ap-south-1
      log_group_name /freelance-client/10/sample-log-generator 
      #log_stream_name <YOUR_LOG_STREAM_NAME>
      auto_create_stream true
      <buffer>
        flush_thread_count 4
        flush_interval 5s
        flush_mode interval
        chunk_limit_size 1m
        queue_limit_length 64
        overflow_action block
      </buffer>
    </match>


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator
          image: alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo 'hi from $(uuidgen) at $(date -Iseconds)'; sleep $LOG_INTERVAL; done"]
          env:
            - name: LOG_INTERVAL
              value: "10"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: log-generator-config

